module.exports = {
	name: "ears",
	aliases: ["im all ears","i'm all ears"],
	wildcard: true,
	nocooldown: true,
	execute(message) {
    	const imagelist = ["https://imgur.com/E5LJhoD", 
			"https://imgur.com/9GL9m70",
			"https://imgur.com/ZcWde1s", 
			"https://imgur.com/C4Qy5rp", 
			"https://imgur.com/nWROOfW",
			"https://imgur.com/7HybEYy",
			"https://imgur.com/AqZWolo",
			"https://imgur.com/2XRjP7E",
			"https://imgur.com/0H0DQvg",
			"https://imgur.com/mBjp5kS",
			"https://imgur.com/4JARohg",
			"https://imgur.com/FldO8GG",
			"https://imgur.com/zYGwmg9",
			"https://imgur.com/PQ9m5HK",
			"https://imgur.com/QD0HSeV",
			"https://imgur.com/YzrNuxr",
			"https://imgur.com/iFQB8jx",
			"https://imgur.com/YMnvtVA",
			"https://imgur.com/g0XH52L",
			"https://imgur.com/r3o6CdS",
			"https://imgur.com/90VTIxL",
			"https://imgur.com/VZ1uwae",
			"https://imgur.com/h2Bekfp",
			"https://i.imgur.com/2gbxc44.gif",
			"https://i.imgur.com/SZ8nJcq.gif",
			"https://imgur.com/wL0zFvY",
			"https://imgur.com/2lnpL2p",
			"https://i.imgur.com/rsR4FZh.gif",
			"https://imgur.com/uZEn8Az",
			"https://imgur.com/884XKsD",
			"https://imgur.com/VddL428",
			"https://i.imgur.com/vfd4oDT.gif",
			"https://imgur.com/yIZQwM6",
			"https://imgur.com/vlT2paH",
			"https://imgur.com/HuXnxwf",
		]
	    const imagenumber = Math.floor(Math.random() * imagelist.length)
        return message.channel.send(imagelist[imagenumber]);
	},
};