module.exports = {
	name: "ears",
	aliases: ["im all ears","i'm all ears"],
	wildcard: true,
	nocooldown: false,
	cooldown_time: 60000,
	execute(message) {
    	const imagelist = ["https://imgur.com/E5LJhoD", 
			"https://imgur.com/9GL9m70",
			"https://imgur.com/ZcWde1s", 
			"https://imgur.com/C4Qy5rp", 
			"https://imgur.com/nWROOfW",
			"https://imgur.com/7HybEYy",
			"https://imgur.com/AqZWolo",
			"https://imgur.com/2XRjP7E",
			"https://imgur.com/0H0DQvg",
			"https://imgur.com/mBjp5kS",
			"https://imgur.com/4JARohg",
			"https://imgur.com/FldO8GG",
			"https://imgur.com/zYGwmg9",
			"https://imgur.com/PQ9m5HK",
			"https://imgur.com/QD0HSeV",
			"https://imgur.com/YzrNuxr",
			"https://imgur.com/iFQB8jx",
			"https://imgur.com/YMnvtVA",
			"https://imgur.com/g0XH52L",
			"https://imgur.com/r3o6CdS",
			"https://imgur.com/90VTIxL",
			"https://imgur.com/VZ1uwae",
			"https://imgur.com/h2Bekfp",
			"https://i.imgur.com/2gbxc44.gif",
			"https://i.imgur.com/SZ8nJcq.gif",
			"https://imgur.com/wL0zFvY",
			"https://imgur.com/2lnpL2p",
			"https://i.imgur.com/rsR4FZh.gif",
			"https://imgur.com/uZEn8Az",
			"https://imgur.com/884XKsD",
			"https://imgur.com/VddL428",
			"https://i.imgur.com/vfd4oDT.gif",
			"https://imgur.com/yIZQwM6",
			"https://imgur.com/vlT2paH",
			"https://imgur.com/HuXnxwf",
			"https://imgur.com/Kdzon4L",
			"https://imgur.com/YiyDr4X",
			"https://imgur.com/NfMiG1f",
			"https://imgur.com/4Q6mheg",
			"https://imgur.com/4Q6mheg",
			"https://imgur.com/stn7fxq",
			"https://imgur.com/7ptrCjW",
			"https://imgur.com/bHz1cwz",
			"https://imgur.com/Z0qOerD",
			"https://imgur.com/xF4XqIL",
			"https://imgur.com/M9KHwJC",
			"https://imgur.com/KdTaqd5",
			"https://imgur.com/HRY5rYv",
			"https://imgur.com/3RbclGG",
			"https://imgur.com/QKS3jnN",
			"https://imgur.com/64FW5wn",
			"https://imgur.com/SNwlH0R",
			"https://imgur.com/A4GAKON",
			"https://imgur.com/5Ue1YCE",
			"https://imgur.com/w7sVYNc",
			"https://imgur.com/VVNrILC",
			"https://imgur.com/oOAN1NI",
			"https://imgur.com/rorbtcH",
			"https://imgur.com/0LRmgH8",
			"https://imgur.com/czFJ3Lh",
			"https://imgur.com/3EGQSFZ",
			"https://imgur.com/HSoqtaC",
			"https://imgur.com/fH2Fcum",
			"https://imgur.com/9GgzfJA",
			"https://imgur.com/PFvL6hN",
			"https://imgur.com/Y50JfId",
			"https://imgur.com/616Ssrw",
			"https://imgur.com/FvnFSJT",
			"https://imgur.com/ZfSpTLw",
			"https://imgur.com/vCAC1MA",
			"https://imgur.com/QfETKJ3"

		]
	    const imagenumber = Math.floor(Math.random() * imagelist.length)
        return message.channel.send(imagelist[imagenumber]);
	},
};