module.exports = {
	name: "seal",
	aliases: [],
	wildcard: true,
	nocooldown: true,
	execute(message) {
		const imagelist = [
			"https://imgur.com/c14mP0k",
			"https://imgur.com/mldS2DA",
			"https://imgur.com/bP8aylA",
			"https://imgur.com/HAxoWZW",
			"https://imgur.com/Du0tajH",
			"https://imgur.com/zYlFBuh",
			"https://imgur.com/ihH0YBp",
			"https://imgur.com/QpjNZFm",
			"https://imgur.com/WxEn7mk",
			"https://imgur.com/a33u8ev",
			"https://imgur.com/f9EeHaH", 
			"https://imgur.com/0CN1q2N",
			"https://imgur.com/N7U6U0S",
			"https://imgur.com/VWZlHTg",
			"https://imgur.com/2MtQLUe",
			"https://imgur.com/qIVUJkC",
			"https://imgur.com/3sZwcCx",
			"https://imgur.com/WQM0JW8",
			"https://imgur.com/7FttC5V",
			"https://imgur.com/AN14hnq",
			"https://imgur.com/sErE8qO",
			"https://imgur.com/wunai8o",
			"https://imgur.com/89LyANp",
			"https://imgur.com/Xse7KRh",
			"https://imgur.com/hEO96Mz",
			"https://imgur.com/OsIh4MH",
			"https://imgur.com/iFLy0eR",
			"https://imgur.com/TNt7rak",
			"https://imgur.com/TthRmn4",
			"https://imgur.com/UL50CXu",
			"https://imgur.com/uEV3aKP",
			"https://imgur.com/KWxpnmy",
			"https://imgur.com/N0TevPa",
			"https://imgur.com/YlB9xTp",
			"https://imgur.com/T6oJ2R5",
			"https://imgur.com/xDHUObN",
			"https://imgur.com/8gf4wqn",
			"https://imgur.com/t9AMaCN",
			"https://imgur.com/e68tXN4",
			"https://imgur.com/ZMgt26j",
			"https://imgur.com/3uqF4Nq",
			"https://imgur.com/u2AlgSe",
			"https://imgur.com/OwMlmaC",
			"https://imgur.com/hxqj2qA",
			"https://imgur.com/lOtMnlp",
			"https://imgur.com/fCgbRH9",
			"https://imgur.com/gXt9r7P",
			"https://imgur.com/Ey3jLtg",
			"https://imgur.com/nE6fNef",
			"https://imgur.com/X3TOWoH",
			"https://imgur.com/sZHBs2s",
			"https://imgur.com/lc37m4s",
			"https://imgur.com/NUs3ri5",
			"https://imgur.com/6vaBQb1",
			"https://imgur.com/f4HWjQD",
			"https://imgur.com/ccd66aH",
			"https://imgur.com/E4GdIxA",
			"https://imgur.com/vtgFZg6",
			"https://imgur.com/maN39Xe",
			"https://imgur.com/gvpcuNT",
			"https://imgur.com/a6z99M5",
			"https://imgur.com/gIkL135",
			"https://imgur.com/oQacyEY",
			"https://imgur.com/LLQ6KWJ",
			"https://imgur.com/7l99A5p",
			"https://imgur.com/FveKZMK",
			"https://imgur.com/35SRiEW",
			"https://imgur.com/W0P9cvf",
			"https://imgur.com/0PIy8QX",
			"https://imgur.com/pK5PXRX",
			"https://imgur.com/CCwGZmu",
			"https://imgur.com/1QP2okc",
			"https://imgur.com/wyNi5ps",
			"https://imgur.com/CqMQuUr",
			"https://imgur.com/vrqzHVq",
			"https://imgur.com/QMEfd5j",
			"https://imgur.com/KHCVOXT",
			"https://imgur.com/ZHmGNmb",
			"https://imgur.com/m3PEyf3",
			"https://imgur.com/0u5VOLA",
			"https://imgur.com/6bhEcYA",
			"https://imgur.com/7Tyvomf",
			"https://imgur.com/TDLyceB",
			"https://imgur.com/RkOIKXw",
			"https://imgur.com/AXOw92H",
			"https://imgur.com/Ewtn7bN",
			"https://imgur.com/JZ1kYkS",
			"https://imgur.com/NaNdI2F",
			"https://imgur.com/39hIS14",
			"https://imgur.com/7y3RShC"
		]
		const imagenumber = Math.floor(Math.random() * imagelist.length)
		return message.channel.send(imagelist[imagenumber]);
			
	},
};
 