module.exports = {
	name: "seal",
	aliases: [],
	wildcard: true,
	nocooldown: true,
	execute(message) {
		const imagelist = [
			"https://imgur.com/c14mP0k",
			"https://imgur.com/mldS2DA",
			"https://imgur.com/bP8aylA",
			"https://imgur.com/HAxoWZW",
			"https://imgur.com/Du0tajH",
			"https://imgur.com/zYlFBuh",
			"https://imgur.com/ihH0YBp",
			"https://imgur.com/QpjNZFm",
			"https://imgur.com/WxEn7mk",
			"https://imgur.com/a33u8ev",
			"https://imgur.com/f9EeHaH", 
			"https://imgur.com/0CN1q2N",
			"https://imgur.com/N7U6U0S",
			"https://imgur.com/VWZlHTg",
			"https://imgur.com/2MtQLUe",
			"https://imgur.com/qIVUJkC",
			"https://imgur.com/3sZwcCx",
			"https://imgur.com/WQM0JW8",
			"https://imgur.com/7FttC5V",
			"https://imgur.com/AN14hnq",
			"https://imgur.com/sErE8qO",
			"https://imgur.com/wunai8o",
			"https://imgur.com/89LyANp",
			"https://imgur.com/Xse7KRh",
			"https://imgur.com/hEO96Mz",
			"https://imgur.com/OsIh4MH",
			"https://imgur.com/iFLy0eR",
			"https://imgur.com/TNt7rak",
			"https://imgur.com/TthRmn4",
			"https://imgur.com/UL50CXu",
			"https://imgur.com/uEV3aKP",
			"https://imgur.com/KWxpnmy",
			"https://imgur.com/N0TevPa",
			"https://imgur.com/YlB9xTp",
			"https://imgur.com/T6oJ2R5",
			"https://imgur.com/xDHUObN",
			"https://imgur.com/8gf4wqn",
			"https://imgur.com/t9AMaCN",
			"https://imgur.com/e68tXN4",
			"https://imgur.com/ZMgt26j",
			"https://imgur.com/3uqF4Nq"
		]
		const imagenumber = Math.floor(Math.random() * imagelist.length)
		return message.channel.send(imagelist[imagenumber]);
			
	},
};
 